### ISSUE TITLE
Free software license

### ISSUE THREAD

**Issue by nzinov** [payala/DeltaTuner#1]
Could you, please, publish your work under some sort of free software license? I would like to modify some of your code

**Comment by payala** [comment]
Hi,

Most probably yes, what license would you propose?

Just out of curiosity, what are you planning to use it for?

Best regards,
Pedro

**Comment by nzinov** [comment]
Any would suite, GPL for example. I would like to use reprapfirmware-lsq
file and build up my calibration routine on top of it

сб, 5 нояб. 2016 г., 17:25 Pedro Perez de Ayala notifications@github.com:

> Hi,
> 
> Most probably yes, what license would you propose?
> 
> Just out of curiosity, what are you planning to use it for?
> 
> Best regards,
> Pedro
>

**Comment by payala** [comment]
Ok, count that I will make it Gnu GPLv3. I started the project to do the
same thing you want to do, but while doing the UI I became busier with
family stuff.

Let me know your repo url so I can follow it.

**Comment by nzinov** [comment]
Thanks, Pedro!

Here is my repo: https://github.com/nzinov/delta_calibrator. I went all in speed and made a very rough program that works for me this time.

**Comment by payala** [comment]
License set.

I'm all for speed too, but this time I wanted to play with some custom controls and kivy.
